# mike
homeassistant:
  name: !secret nameid
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_local
  packages: !include_dir_named integrations
  whitelist_external_dirs:
    - !secret home
    - !secret data

# Default config alternative
config:
frontend:
sun:
map:
mobile_app:
ssdp:
zeroconf:
updater:
system_health:

# Access config
http:
  base_url: !secret http_url
  server_port: !secret http_port
  ip_ban_enabled: True
  login_attempts_threshold: 10
# Person config
person:

# History config
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date

# Logbook config
logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
    domains:
      - sun
      - weblink
# Logger config
logger:
  default: info
  logs:
