title: MyTestHomeAssistant
views:

  - title: Глагне
    icon: mdi:home-assistant

    cards:

      - type: vertical-stack
        cards:

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Времечко
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Date
              icon: mdi:calendar-check-outline


  - title: Погодка
    icon: mdi:weather-partly-snowy-rainy

  - title: Видеонаблюдение
    icon: mdi:cctv

    cards: 

      - type: glance
        title: SensorPanel
        entities:
          - binary_sensor.sensor_hc_sr501
      - type: button
        name: Relay_Button
        initial_state: false
        tap_action:
          - action: call-service
            entity_id: binary_sensor.relay

          

        

      #- type: picture-glance
      #  title: Camera
      #  entities:
      #    - camera.raspberry_pi_camera
      #    - binary_sensor.sensor_hc_sr501
      #  camera_image: camera.raspberry_pi_camera

      #- type: picture-entity
      # entity: camera.raspberry_pi_camera
      #  camera_view: live



